version: 2.1

references:
  x-workdir: &work-dir
    working_directory: ~/source

  x-save-workspace: &persist-step
    persist_to_workspace:
      root: ~/source
      paths:
        - .

  x-attach: &attach-step
    attach_workspace:
      at: .

jobs:
  install-dependencies:
    <<: *work-dir
    docker:
      - image: circleci/node:10
    environment:
      HUSKY_SKIP_INSTALL: 1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-npm-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: |
            if [ ! -d node_modules ]; then
                npm ci
            fi
      - save_cache:
          key: v2-npm-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - *persist-step

workflows:
  version: 2
  sinon-workflow:
    jobs:
      - install-dependencies
