version: 2
jobs:
  build-common: &common-build
    docker:
      - image: node
    working_directory: ~/sinon
    steps:
      - run:
          name: Versions
          command: |
            npm version
      - checkout
      - restore_cache:
          keys:
            - v1-npm-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-npm-master-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: |
              npm config set strict-ssl false
              npm install
      - run:
          name: Test
          command: npm run test-node
      - save_cache:
          key: v1-npm-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules

  build-node4:
    <<: *common-build
    docker:
      - image: node:4

  build-node6:
    <<: *common-build
    docker:
      - image: node:6

  build-node8:
    <<: *common-build
    docker:
      - image: node:8

workflows:
  version: 2
  build:
    jobs:
      - build-node4
      - build-node6
      - build-node8
