title: Sinon.JS
<<<<<<< HEAD
description: Standalone test spies, stubs and mocks for JavaScript. Works with any unit testing framework.
=======
description: 'Standalone test spies, stubs and mocks for JavaScript. Works with any unit testing framework.'
>>>>>>> 9157d41cd95cb29ea1154083787df2406f2b37cc
url: 'http://sinonjs.org'
github_username: sinonjs
sinon:
  current_release: v2.1.0
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: none
  syntax_highlighter_opts:
    disable: true
gems:
  - jekyll-feed
  - jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock
  - release-source
collections:
  howto:
    output: true
    permalink: '/how-to/:path/'
  releases:
    output: true
    permalink: '/:collection/:path/'
sass:
  sass_dir: _sass
  style: compressed
